server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
    context-path: /

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true

  main:
    allow-bean-definition-overriding: true
  mvc:
    resources:
      static-locations: classpath:/static
    static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace